import type { Output, Reviewer, RoleModel, UpcomingPerson, Input } from './types'
import { subDays, subHours } from 'date-fns'

const now = new Date()
const USER_ID = 'local-user'

export const DUMMY_OUTPUTS: Output[] = [
  {
    id: '1',
    user_id: USER_ID,
    title: '起業家思考法 書評',
    type: 'article',
    self_score: 7.0,
    memo: '本の要点を整理できたが、自分の経験との接続が弱い',
    created_at: subHours(now, 3).toISOString(),
  },
  {
    id: '2',
    user_id: USER_ID,
    title: 'MTG発言 (新企画案)',
    type: 'speech',
    self_score: 5.5,
    memo: '準備不足で具体性に欠けた',
    created_at: subDays(now, 1).toISOString(),
    reviewer_id: 'r1',
    peer_score: 7.0,
    peer_note: '視点が新鮮で良かった',
    peer_scored_at: subDays(now, 1).toISOString(),
  },
  {
    id: '3',
    user_id: USER_ID,
    title: 'プロトタイプ v0.2',
    type: 'product',
    self_score: 8.0,
    created_at: subDays(now, 3).toISOString(),
    reviewer_id: 'r2',
    peer_score: 6.5,
    peer_note: 'UIは良いが機能が不足',
    peer_scored_at: subDays(now, 2).toISOString(),
  },
  {
    id: '4',
    user_id: USER_ID,
    title: 'ブログ記事: ADHDと起業',
    type: 'post',
    self_score: 6.0,
    created_at: subDays(now, 4).toISOString(),
    reviewer_id: 'r1',
    peer_score: 7.5,
    peer_scored_at: subDays(now, 3).toISOString(),
  },
  {
    id: '5',
    user_id: USER_ID,
    title: '8M分析シート作成',
    type: 'product',
    self_score: 7.5,
    created_at: subDays(now, 5).toISOString(),
  },
  {
    id: '6',
    user_id: USER_ID,
    title: '朝活プレゼン: 別解力',
    type: 'speech',
    self_score: 6.5,
    created_at: subDays(now, 5).toISOString(),
    reviewer_id: 'r3',
    peer_score: 8.0,
    peer_scored_at: subDays(now, 5).toISOString(),
  },
  {
    id: '7',
    user_id: USER_ID,
    title: 'Notionテンプレート共有',
    type: 'other',
    self_score: 5.0,
    created_at: subDays(now, 6).toISOString(),
  },
  {
    id: '8',
    user_id: USER_ID,
    title: '企画書ドラフト',
    type: 'article',
    self_score: 7.0,
    created_at: subDays(now, 6).toISOString(),
  },
  {
    id: '9',
    user_id: USER_ID,
    title: 'チーム1on1フィードバック',
    type: 'speech',
    self_score: 6.0,
    created_at: subDays(now, 2).toISOString(),
  },
  {
    id: '10',
    user_id: USER_ID,
    title: 'SNS投稿: 学びの共有',
    type: 'post',
    self_score: 5.5,
    created_at: subDays(now, 1).toISOString(),
  },
  {
    id: '11',
    user_id: USER_ID,
    title: 'API設計レビュー',
    type: 'product',
    self_score: 7.5,
    created_at: subDays(now, 4).toISOString(),
  },
  {
    id: '12',
    user_id: USER_ID,
    title: '失敗ログ: 提案却下分析',
    type: 'article',
    self_score: 8.0,
    created_at: subDays(now, 3).toISOString(),
  },
]

export const DUMMY_REVIEWERS: Reviewer[] = [
  { id: 'r1', user_id: USER_ID, name: '佐藤さん', relationship: 'boss' },
  { id: 'r2', user_id: USER_ID, name: '鈴木さん', relationship: 'peer' },
  { id: 'r3', user_id: USER_ID, name: '高橋さん', relationship: 'mentor' },
]

export const DUMMY_ROLE_MODELS: RoleModel[] = [
  {
    id: 'rm1',
    user_id: USER_ID,
    name: '平尾丈',
    initials: '平尾',
    color_key: 'purple',
    learning_notes: [
      { at: subDays(now, 1).toISOString(), text: '別解は3要素の重なりから生まれる' },
    ],
    created_at: subDays(now, 30).toISOString(),
  },
  {
    id: 'rm2',
    user_id: USER_ID,
    name: 'A.スミス',
    initials: 'AS',
    color_key: 'teal',
    learning_notes: [],
    created_at: subDays(now, 20).toISOString(),
  },
  {
    id: 'rm3',
    user_id: USER_ID,
    name: '藤原氏',
    initials: '藤原',
    color_key: 'coral',
    learning_notes: [],
    created_at: subDays(now, 15).toISOString(),
  },
  {
    id: 'rm4',
    user_id: USER_ID,
    name: '中村氏',
    initials: '中村',
    color_key: 'amber',
    learning_notes: [],
    created_at: subDays(now, 10).toISOString(),
  },
]

export const DUMMY_UPCOMING_PEOPLE: UpcomingPerson[] = [
  {
    id: 'up1',
    user_id: USER_ID,
    name: '田中さん',
    meeting_date: '2026-06-02',
    questions: [
      '事業の転換点で最も重要だった判断は？',
      'チームのモチベーション管理で心がけていることは？',
      '失敗から学んだ最大の教訓は？',
      '20代の自分にアドバイスするなら？',
      'インプットで最も重視しているメディアは？',
      '意思決定のフレームワークはあるか？',
      '別解を出すために日常で意識していることは？',
    ],
    met: false,
  },
]

export const DUMMY_INPUTS: Input[] = [
  {
    id: 'i1',
    user_id: USER_ID,
    type: 'book',
    title: '起業家の思考法',
    learning: '別解の重要性と5つの力',
    created_at: subDays(now, 1).toISOString(),
  },
  {
    id: 'i2',
    user_id: USER_ID,
    type: 'book',
    title: 'ゼロ・トゥ・ワン',
    created_at: subDays(now, 3).toISOString(),
  },
  {
    id: 'i3',
    user_id: USER_ID,
    type: 'article',
    title: 'スタートアップの成長戦略',
    created_at: subDays(now, 1).toISOString(),
  },
  {
    id: 'i4',
    user_id: USER_ID,
    type: 'article',
    title: 'プロダクト開発の失敗パターン',
    created_at: subDays(now, 2).toISOString(),
  },
  {
    id: 'i5',
    user_id: USER_ID,
    type: 'article',
    title: 'リーダーシップ論',
    created_at: subDays(now, 3).toISOString(),
  },
  {
    id: 'i6',
    user_id: USER_ID,
    type: 'article',
    title: 'ADHD起業家の強み',
    created_at: subDays(now, 4).toISOString(),
  },
  {
    id: 'i7',
    user_id: USER_ID,
    type: 'article',
    title: 'マーケティング戦略2026',
    created_at: subDays(now, 5).toISOString(),
  },
  {
    id: 'i8',
    user_id: USER_ID,
    type: 'article',
    title: 'AIプロダクト開発入門',
    created_at: subDays(now, 5).toISOString(),
  },
  {
    id: 'i9',
    user_id: USER_ID,
    type: 'article',
    title: 'フレームワーク思考の実践',
    created_at: subDays(now, 6).toISOString(),
  },
  {
    id: 'i10',
    user_id: USER_ID,
    type: 'article',
    title: 'ポータブルスキルの磨き方',
    created_at: subDays(now, 6).toISOString(),
  },
  {
    id: 'i11',
    user_id: USER_ID,
    type: 'video',
    title: 'まこなり社長: 起業家思考法レビュー',
    created_at: subDays(now, 2).toISOString(),
  },
  {
    id: 'i12',
    user_id: USER_ID,
    type: 'video',
    title: 'TED: 失敗の科学',
    created_at: subDays(now, 4).toISOString(),
  },
  {
    id: 'i13',
    user_id: USER_ID,
    type: 'video',
    title: 'Y Combinator: How to Get Ideas',
    created_at: subDays(now, 5).toISOString(),
  },
  {
    id: 'i14',
    user_id: USER_ID,
    type: 'dialogue',
    title: '佐藤さんとの1on1',
    created_at: subDays(now, 1).toISOString(),
  },
  {
    id: 'i15',
    user_id: USER_ID,
    type: 'dialogue',
    title: 'メンター面談',
    created_at: subDays(now, 3).toISOString(),
  },
  {
    id: 'i16',
    user_id: USER_ID,
    type: 'dialogue',
    title: '朝活ディスカッション',
    created_at: subDays(now, 4).toISOString(),
  },
  {
    id: 'i17',
    user_id: USER_ID,
    type: 'dialogue',
    title: 'チームブレスト',
    created_at: subDays(now, 5).toISOString(),
  },
  {
    id: 'i18',
    user_id: USER_ID,
    type: 'dialogue',
    title: '異業種交流会',
    created_at: subDays(now, 6).toISOString(),
  },
]
